// ── Dynamic WO registry — holds locally-created work orders ───────────────
const _dynamic = {}
export function registerWO(wo) { _dynamic[wo.id] = wo }
export function getWO(id)      { return WORK_ORDERS[id] ?? _dynamic[id] ?? null }

export const TECHNICIAN = {
  name: 'Jake Thibodaux',
  role: 'Field Technician — Fast Track',
  roleNote: 'Fast Track — under 18 months experience',
  branch: 'New Orleans, LA',
  avatar: 'JT',
  workOrders: ['WO-2847', 'WO-2853', 'WO-2856', 'WO-2851', 'WO-2854', 'WO-2855'],
}

export const ADMIN = {
  name: 'Sandra Arceneaux',
  role: 'Service Manager',
  branch: 'Gulf Coast Region',
  avatar: 'SA',
}

export const KB_SEARCH_RESULTS = [
  {
    keywords: ['brake', 'air gap', 'drift', 'motor brake', 'hook drift'],
    title: 'Motor Brake Adjustment Procedure',
    source: 'Shaw-Box 800 Series Manual',
    section: 'Section 7-2, p.23',
    snippet: '"When gap reaches .200" it will need to be readjusted to .100". Friction disc should be replaced when wear area is 3/32" thick or less."',
  },
  {
    keywords: ['wire rope', 'rope inspection', 'broken wire', 'corrosion'],
    title: 'Wire Rope Inspection Criteria',
    source: 'Shaw-Box 800 Series Manual',
    section: 'Section 4-1, p.8',
    snippet: 'Replace wire rope if broken wires exceed 2 in any 6-rope-diameter length, or if kinking, crushing, bird-caging, or corrosion is present.',
  },
  {
    keywords: ['contactor', 'coil', 'relay', 'won\'t raise', 'up button'],
    title: 'Contactor Inspection & Replacement',
    source: 'Yale Y80 Series Manual',
    section: 'Section 6-4, p.19',
    snippet: '"Verify that the contactor armatures are free to move. If binding occurs, replace contactor. Check for burned out contactor coils."',
  },
  {
    keywords: ['loto', 'lockout', 'tagout', 'lockout tagout', 'osha'],
    title: 'Lockout / Tagout Procedure',
    source: 'OSHA 29 CFR 1910.147',
    section: 'Control of Hazardous Energy',
    snippet: 'Lock the main power switch in the open (OFF) position and tag per OSHA 29 CFR 1910.147 before beginning any inspection or maintenance.',
  },
  {
    keywords: ['fuse', 'transformer', 'no power', 'won\'t operate', 'ppd', 'phase'],
    title: 'Control Power Loss Diagnosis',
    source: 'World Series Double Girder Manual',
    section: 'Section 6-1, p.22',
    snippet: '"Check transformer fuse. If blown, check for grounding and/or shorts in push button station. Check transformer coil for signs of overheating."',
  },
  {
    keywords: ['overload', 'clutch', 'slipping', 'capacity', 'rated load'],
    title: 'Overload Clutch & Rated Capacity',
    source: 'Shaw-Box 800 Series Manual',
    section: 'Section 6-7, p.20',
    snippet: '"Excessive load — Reduce loading to rated load as shown on nameplate." Never adjust the overload clutch to compensate for overloading.',
  },
]

export const WORK_ORDERS = {
  'WO-2847': {
    id: 'WO-2847',
    status: 'In Progress',
    priority: 'High',
    customer: 'Westlake Chemical',
    site: 'Sulphur, LA',
    equipment: 'Shaw-Box Series 800 — 2-Ton Wire Rope Hoist',
    serialNumber: 'SB800-2T-4471',
    complaint: 'Load drifting excessively when hoist stops. Hook drops several inches before coming to rest.',
    jobType: 'Emergency Repair',
    scheduledDate: 'Today, 8:00 AM',
    lastService: '6 months ago — routine PM',
    hoursOnUnit: 487,
    aiReady: true,
    aiContext: 'Matched against 3 similar fault reports in Gulf Coast fleet. Brake friction washers replaced 10 months ago — within normal re-wear range. Prior PM (Jan 2025) recorded gap at 0.120\" — consistent with progressive wear to current complaint.',
    equipmentHistory: [
      {
        date: 'Jan 14, 2025',
        type: 'Routine PM',
        tech: 'R. Fontenot',
        findings: 'Brake air gap measured at 0.120\". All components within spec. Wire rope inspected — no deficiencies found.',
        partsUsed: 'None',
        hours: 312,
      },
      {
        date: 'Jul 22, 2024',
        type: 'Corrective Repair',
        tech: 'J. Thibodaux',
        findings: 'Load brake friction washers replaced due to glazing. Motor brake adjusted to 0.100\" air gap. Test run confirmed — no drift.',
        partsUsed: 'Friction Washer (x2) — Part No. 800-235',
        hours: 289,
      },
      {
        date: 'Feb 8, 2024',
        type: 'Routine PM',
        tech: 'R. Fontenot',
        findings: 'Full inspection completed. Hoist operating within all specifications. Hook, load chain, and wire rope in serviceable condition.',
        partsUsed: 'Hook latch spring',
        hours: 201,
      },
    ],
    predictions: [
      {
        rank: 1,
        fault: 'Motor brake disc worn — air gap exceeds 0.200"',
        confidence: 87,
        part: 'Friction Disc Kit — Part No. 800-5005',
        source: 'Shaw-Box 800 Series Manual, Section 7-2 (Motor Brake Adjustment), p.23',
        citation: '"When gap reaches .200" it will need to be readjusted to .100". Friction disc should be replaced when wear area is 3/32" thick or less."',
        severity: 'HIGH',
        safetyWarning: 'LOCKOUT/TAGOUT required before removing brake cover. ANSI B30.16 compliance mandatory.',
      },
      {
        rank: 2,
        fault: 'Load brake friction washers worn or glazed',
        confidence: 71,
        part: 'Friction Washer (x2) — Part No. 800-235',
        source: 'Shaw-Box 800 Series Manual, Section 5-6 (Inspect Mechanical Load Brake), p.11',
        citation: '"Hard surface or glazed friction discs should be replaced." Load brake assembly Part No. 800-230.',
        severity: 'MEDIUM',
        safetyWarning: 'Drain gearcase oil before inspection. Do not operate hoist with load brake deficiency.',
      },
      {
        rank: 3,
        fault: 'Load exceeding rated capacity — overload clutch slipping',
        confidence: 38,
        part: null,
        source: 'Shaw-Box 800 Series Manual, Section 6-7 (Trouble Shooting), p.20',
        citation: '"Excessive load — Reduce loading to rated load as shown on nameplate."',
        severity: 'LOW',
        safetyWarning: 'Never lift more than rated load. Check nameplate for rated capacity.',
      },
    ],
    adaptiveQuestions: [
      {
        question: 'Does the hook drift with NO load on it, or only when a load is attached?',
        options: ['Drifts with no load', 'Only drifts with load', 'Both'],
        impact: {
          'Drifts with no load': 'Motor brake only — adjusted air gap likely sufficient (+12% on fault 1)',
          'Only drifts with load': 'Load brake primary suspect (+18% on fault 2)',
          Both: 'Both systems compromised — escalate to service manager',
        },
        confidenceShift: {
          'Drifts with no load': [12, -5, 0],
          'Only drifts with load': [-8, 18, 0],
          Both: [5, 8, 0],
        },
      },
      {
        question: 'Does the hook drift slowly, or does it drop suddenly?',
        options: ['Slow gradual drift', 'Sudden drop'],
        impact: {
          'Slow gradual drift': 'Wear-related — brake adjustment likely sufficient',
          'Sudden drop': 'Mechanical failure — immediate removal from service required',
        },
        confidenceShift: {
          'Slow gradual drift': [8, 4, -5],
          'Sudden drop': [5, -3, 0],
        },
      },
    ],
    resolutionSteps: [
      { step: 1, text: 'LOCKOUT/TAGOUT: Lock main power switch in open (OFF) position. Tag per OSHA 29 CFR 1910.147.', isLoto: true, isSafety: true },
      { step: 2, text: 'Check air gap: Remove brake cover (Part No. 800-5007). Measure air gap between brake disc and friction surface.', isLoto: false, isSafety: false },
      { step: 3, text: 'Assess gap: Factory setting is 0.100". If gap has reached 0.200", adjustment is required.', isLoto: false, isSafety: false },
      { step: 4, text: 'Adjust: Loosen jam nut (10N). Turn adjusting screw (10) CW until 0.100" gap is reached. Retighten jam nut.', isLoto: false, isSafety: false },
      { step: 5, text: 'If friction disc worn to 3/32" or less: Replace disc (Part No. 800-5005). Requires brake disassembly per Section 7-2.', isLoto: false, isSafety: true },
      { step: 6, text: 'Reinstall brake cover. Tighten to 8 lb-in clockwise.', isLoto: false, isSafety: false },
      { step: 7, text: 'Test: Remove lockout. Run hoist with rated load. Hook should stop immediately with zero drift on button release.', isLoto: false, isSafety: true },
      { step: 8, text: 'Document: Record findings on Inspection Schedule form. OSHA requires written, dated, signed reports.', isLoto: false, isSafety: false },
    ],
    parts: 'Friction Disc Kit — Part No. 800-5005',
    sourceRef: 'Shaw-Box 800 Series Manual, Section 7-2, p.23',
    faultLabel: 'Motor Brake Adjustment',
    jobTime: '~52 min',
    defaultNote: 'Measured motor brake air gap at 0.210". Replaced friction disc (Part No. 800-5005). Gap adjusted to 0.100". Test run — zero drift confirmed on button release.',
  },

  'WO-2851': {
    id: 'WO-2851',
    status: 'Scheduled',
    priority: 'Medium',
    customer: 'Dow Chemical',
    site: 'Freeport, TX',
    equipment: 'Yale Y80 Series — 3-Ton Wire Rope Hoist',
    serialNumber: 'Y80-3T-8821',
    complaint: 'Hook will lower but will not raise. UP button press produces no movement.',
    jobType: 'Corrective Repair',
    scheduledDate: 'Tomorrow, 7:30 AM',
    lastService: '3 months ago',
    hoursOnUnit: 612,
    aiReady: true,
    aiContext: 'March 2025 PM note flagged oxidation on UP contactor contacts — cleaned but not replaced. Pattern consistent with progressive electrical degradation. 68 hours of operation since last service.',
    equipmentHistory: [
      {
        date: 'Mar 3, 2025',
        type: 'Routine PM',
        tech: 'J. Thibodaux',
        findings: 'Full PM completed. Contactor assemblies inspected — slight oxidation on UP contactor contacts. Cleaned and tested. All functions normal.',
        partsUsed: 'Contact cleaner spray',
        hours: 544,
      },
      {
        date: 'Sep 18, 2024',
        type: 'Routine PM',
        tech: 'D. Broussard',
        findings: 'Wire rope inspection: no deficiencies. Hook and latch in good condition. Brake adjusted — air gap 0.100".',
        partsUsed: 'None',
        hours: 401,
      },
    ],
    predictions: [
      {
        rank: 1,
        fault: 'Contactor assembly binding or coil burned out',
        confidence: 82,
        part: 'Contactor — Part No. 800-656',
        source: 'Yale Y80 Series Manual, Section 6-4 (Hook Will Lower But Not Raise), p.19',
        citation: '"Verify that the contactor armatures are free to move. If binding occurs, replace contactor. Check for burned out contactor coils."',
        severity: 'HIGH',
        safetyWarning: 'Disconnect and lockout power before opening electrical compartment cover.',
      },
      {
        rank: 2,
        fault: 'UP push button contacts worn or wiring fault',
        confidence: 64,
        part: 'Push Button Station — Part No. BH-4028',
        source: 'Yale Y80 Series Manual, Section 6-4, p.19',
        citation: '"Check push button contacts and wires." Push Button Station Assembly Part No. BH-4027.',
        severity: 'MEDIUM',
        safetyWarning: 'Test with power OFF first. Inspect wiring insulation for damage.',
      },
      {
        rank: 3,
        fault: 'Motor overheated — thermal protection tripped',
        confidence: 41,
        part: null,
        source: 'Yale Y80 Series Manual, Section 6-4 and 6-6, p.19–20',
        citation: '"Excessive duty-cycle — reduce frequency of lifts or amount of jogging." Allow cooling period before retry.',
        severity: 'LOW',
        safetyWarning: null,
      },
    ],
    adaptiveQuestions: [
      {
        question: 'When you press the UP button, do you hear the contactor click?',
        options: ['Yes — click but no movement', 'No — completely silent', 'Intermittent click'],
        impact: {
          'Yes — click but no movement': 'Contactor energising but motor not responding — check motor windings (+10% on fault 1)',
          'No — completely silent': 'Contactor coil likely burned out — replace contactor (+15% on fault 1)',
          'Intermittent click': 'Contactor armature binding — inspect and clean armature (+8% on fault 1)',
        },
        confidenceShift: {
          'Yes — click but no movement': [10, -5, -3],
          'No — completely silent': [15, -8, 0],
          'Intermittent click': [8, 0, -5],
        },
      },
      {
        question: 'Is the thermal overload indicator tripped on the motor housing?',
        options: ['Yes — red indicator showing', 'No — indicator clear'],
        impact: {
          'Yes — red indicator showing': 'Motor overheated — allow 30-min cooling period before retry (+20% on fault 3)',
          'No — indicator clear': 'Thermal protection clear — focus on contactor and push button (+10% on fault 1)',
        },
        confidenceShift: {
          'Yes — red indicator showing': [-10, -5, 20],
          'No — indicator clear': [10, 5, -10],
        },
      },
    ],
    resolutionSteps: [
      { step: 1, text: 'LOCKOUT/TAGOUT: Lock main power switch in open (OFF) position. Tag per OSHA 29 CFR 1910.147.', isLoto: true, isSafety: true },
      { step: 2, text: 'Open electrical compartment cover. Inspect for visible signs of burning, heat damage, or loose wiring.', isLoto: false, isSafety: true },
      { step: 3, text: 'Check contactor assembly: verify armatures are free to move. Manually depress armature — it should move freely with no binding.', isLoto: false, isSafety: false },
      { step: 4, text: 'Inspect contactor coil for signs of burning or discolouration. If burned, replace contactor assembly (Part No. 800-656).', isLoto: false, isSafety: false },
      { step: 5, text: 'Test UP push button contacts with multimeter. Check for continuity when button pressed. Inspect wiring insulation for damage.', isLoto: false, isSafety: false },
      { step: 6, text: 'Reinstall electrical cover. Ensure all wire connections are tight and correctly seated.', isLoto: false, isSafety: false },
      { step: 7, text: 'Remove LOTO. Restore power. Test UP and DOWN operation through full travel with rated load.', isLoto: false, isSafety: true },
      { step: 8, text: 'Document: Record all findings, parts replaced, and test results on Inspection Schedule form. OSHA requires written, dated, signed reports.', isLoto: false, isSafety: false },
    ],
    parts: 'Contactor — Part No. 800-656',
    sourceRef: 'Yale Y80 Series Manual, Section 6-4, p.19',
    faultLabel: 'Contactor Inspection & Replacement',
    jobTime: '~38 min',
    defaultNote: 'Inspected contactor assembly — UP contactor coil burned out. Replaced contactor (Part No. 800-656). Tested UP/DOWN through full travel with rated load. All functions normal.',
  },

  'WO-2853': {
    id: 'WO-2853',
    status: 'Scheduled',
    priority: 'High',
    customer: 'LyondellBasell',
    site: 'Houston, TX',
    equipment: 'World Series Double Girder Bridge Crane — 10-Ton',
    serialNumber: 'WS3D-10T-2204',
    complaint: 'Entire hoist will not operate. No response on any controls. No sounds when pushbuttons pressed.',
    jobType: 'Emergency Repair',
    scheduledDate: 'Today, 2:00 PM',
    lastService: '11 months ago',
    hoursOnUnit: 934,
    aiReady: true,
    aiContext: 'Control transformer replaced Jan 2024 after overvoltage event — same unit, recurring control power failure pattern. Surge protection added at that service. 173 hours since last inspection.',
    equipmentHistory: [
      {
        date: 'Jul 8, 2024',
        type: 'Annual Inspection',
        tech: 'M. Guidry',
        findings: 'Full ASME B30.2 annual inspection completed. All mechanical and electrical systems within spec. PPD tested and functional. Wire rope: 18 months remaining service life estimated.',
        partsUsed: 'Limit switch cam',
        hours: 761,
      },
      {
        date: 'Jan 22, 2024',
        type: 'Corrective Repair',
        tech: 'D. Broussard',
        findings: 'Control transformer replaced after coil overheated. Root cause: sustained overvoltage event. Added surge protection to incoming power line.',
        partsUsed: 'Control Transformer — Part No. 800-671, Surge protector',
        hours: 698,
      },
    ],
    predictions: [
      {
        rank: 1,
        fault: 'No control voltage — transformer fuse blown',
        confidence: 79,
        part: 'Fuse & Transformer — Part No. 800-673 / 800-671',
        source: 'World Series Double Girder Trolley Manual, Section 6-1 (Hoist Will Not Operate), p.22',
        citation: '"Check transformer fuse. If blown, check for grounding and/or shorts in push button station. Check transformer coil for signs of overheating."',
        severity: 'HIGH',
        safetyWarning: 'Lock out power before removing electrical cover. Check for signs of burning or overheating before energising.',
      },
      {
        rank: 2,
        fault: 'Phase protection device (PPD) tripped — amber LED steady',
        confidence: 65,
        part: null,
        source: 'World Series Double Girder Trolley Manual, Section 6-1, p.22',
        citation: '"Check phase protection device (PPD), if amber LED is steady; interchange any two power supply line leads."',
        severity: 'MEDIUM',
        safetyWarning: 'Do not interchange leads without confirming correct phasing with a qualified electrician.',
      },
      {
        rank: 3,
        fault: 'Loose or broken wire connections — electrical compartment',
        confidence: 44,
        part: null,
        source: 'World Series Double Girder Trolley Manual, Section 6-1, p.22',
        citation: '"Shut off and lock out power supply; remove electrical cover and check wiring connections. Also check connections in push button station and limit switches."',
        severity: 'LOW',
        safetyWarning: 'Full LOTO required. Written, dated inspection report mandatory per OSHA regulations.',
      },
    ],
    adaptiveQuestions: [
      {
        question: 'Is the amber LED on the Phase Protection Device (PPD) steady, flashing, or off?',
        options: ['Steady amber', 'Flashing amber', 'LED off'],
        impact: {
          'Steady amber': 'Phase sequence reversed — interchange any two power supply line leads (+20% on fault 2)',
          'Flashing amber': 'Phase loss detected — check incoming power connections',
          'LED off': 'No control voltage reaching PPD — transformer fuse likely blown (+15% on fault 1)',
        },
        confidenceShift: {
          'Steady amber': [-10, 20, 0],
          'Flashing amber': [5, 8, 0],
          'LED off': [15, -5, 0],
        },
      },
      {
        question: 'Is there a burning smell or visible scorch marks near the electrical compartment?',
        options: ['Yes — burning smell or marks visible', 'No — no signs of burning'],
        impact: {
          'Yes — burning smell or marks visible': 'Transformer coil overheated — replace transformer before re-energising (+12% on fault 1)',
          'No — no signs of burning': 'Fuse only likely — replace fuse and retest (+8% on fault 1)',
        },
        confidenceShift: {
          'Yes — burning smell or marks visible': [12, 0, 5],
          'No — no signs of burning': [8, 0, -3],
        },
      },
    ],
    resolutionSteps: [
      { step: 1, text: 'LOCKOUT/TAGOUT: Lock main power switch in open (OFF) position. Tag per OSHA 29 CFR 1910.147. Check for burning before opening any panel.', isLoto: true, isSafety: true },
      { step: 2, text: 'Open electrical compartment cover. Inspect for burning, heat damage, loose connections, or signs of short circuit.', isLoto: false, isSafety: true },
      { step: 3, text: 'Locate and inspect transformer fuse (Part No. 800-673). If blown, check entire control circuit for shorts or grounds before replacing.', isLoto: false, isSafety: false },
      { step: 4, text: 'Inspect transformer coil (Part No. 800-671) for signs of overheating or discolouration. Replace transformer if damaged.', isLoto: false, isSafety: false },
      { step: 5, text: 'Check Phase Protection Device (PPD) LED: if amber steady, interchange any two power supply line leads. Confirm phasing with qualified electrician.', isLoto: false, isSafety: true },
      { step: 6, text: 'Inspect all wiring connections in electrical compartment, push button station, and limit switches. Tighten any loose connections.', isLoto: false, isSafety: false },
      { step: 7, text: 'Replace blown fuse (Part No. 800-673). Reinstall all covers. Remove LOTO and restore power.', isLoto: false, isSafety: true },
      { step: 8, text: 'Test all controls: hoist UP/DOWN, bridge travel, and limit switches. Document all findings per OSHA requirements.', isLoto: false, isSafety: false },
    ],
    parts: 'Fuse & Transformer — Part No. 800-673 / 800-671',
    sourceRef: 'World Series Double Girder Trolley Manual, Section 6-1, p.22',
    faultLabel: 'Control Power & Electrical Diagnosis',
    jobTime: '~65 min',
    defaultNote: 'Found transformer fuse blown (Part No. 800-673). Inspected control circuit for shorts — none found. Replaced fuse and transformer coil (Part No. 800-671). PPD LED green. All controls tested and operational.',
  },

  'WO-2854': {
    id: 'WO-2854',
    status: 'Scheduled',
    priority: 'Medium',
    customer: 'Huntsman Chemical',
    site: 'Port Arthur, TX',
    equipment: 'Yale Y45 Series — 1-Ton Electric Chain Hoist',
    serialNumber: 'Y45-1T-3392',
    complaint: 'Quarterly preventive maintenance due. Unit is operational — PM interval reached at 228 hours.',
    jobType: 'Routine PM',
    scheduledDate: 'Tomorrow, 10:00 AM',
    lastService: '3 months ago — quarterly PM',
    hoursOnUnit: 228,
    aiReady: true,
    aiContext: 'Unit is at 228 hours — within the 250-hour quarterly PM window. Previous PM by R. Fontenot noted chain elongation approaching lower threshold. Chain stretch is the priority check this visit.',
    equipmentHistory: [
      {
        date: 'Feb 14, 2026',
        type: 'Quarterly PM',
        tech: 'J. Thibodaux',
        findings: 'Chain measured at 1.6% elongation — within spec. Brake air gap 0.085". All limit switches functional. No deficiencies found.',
        partsUsed: 'Chain lubricant',
        hours: 172,
      },
      {
        date: 'Nov 12, 2025',
        type: 'Quarterly PM',
        tech: 'R. Fontenot',
        findings: 'Full PM completed. Chain elongation 1.2%. Brake adjusted to 0.080". Hook and latch in serviceable condition.',
        partsUsed: 'None',
        hours: 118,
      },
    ],
    predictions: [
      {
        rank: 1,
        fault: 'Chain elongation approaching replacement threshold — stretch gauge required',
        confidence: 71,
        part: 'Load Chain — Part No. Y45-C10 (if replacement required)',
        source: 'Yale Y45 Series Manual, Section 4-3 (Chain Inspection), p.14',
        citation: '"Measure chain for elongation using a chain wear gauge. Replace if link pitch exceeds 3% over nominal length. Do not use a chain that fails this test."',
        severity: 'MEDIUM',
        safetyWarning: 'Inspect chain under no-load conditions only. A worn chain can fail suddenly under load.',
      },
      {
        rank: 2,
        fault: 'Brake air gap — measure and adjust if outside 0.060"–0.180" range',
        confidence: 55,
        part: null,
        source: 'Yale Y45 Series Manual, Section 5-2 (Motor Brake), p.18',
        citation: '"Check motor brake air gap every 250 operating hours. Adjust to 0.090" if gap exceeds 0.180". Replace friction disc if worn to 2mm or less."',
        severity: 'LOW',
        safetyWarning: null,
      },
      {
        rank: 3,
        fault: 'Hook latch spring — inspect for set, fatigue, or reduced tension',
        confidence: 38,
        part: 'Hook Latch Spring — Part No. Y45-112',
        source: 'Yale Y45 Series Manual, Section 3-1 (Hook Inspection), p.9',
        citation: '"Inspect hook latch for free operation. Latch must return to closed position under spring tension alone. Replace spring if latch does not close fully."',
        severity: 'LOW',
        safetyWarning: null,
      },
    ],
    adaptiveQuestions: [
      {
        question: 'Is there any visible chain discolouration, corrosion, or damaged links?',
        options: ['Discolouration or corrosion visible', 'Damaged link found', 'No visible issues'],
        impact: {
          'Discolouration or corrosion visible': 'Chain requires close measurement — possible early replacement (+10% on fault 1)',
          'Damaged link found': 'Chain must be replaced immediately — remove from service',
          'No visible issues': 'Proceed with stretch measurement as planned',
        },
        confidenceShift: {
          'Discolouration or corrosion visible': [10, 0, 0],
          'Damaged link found': [25, 0, 0],
          'No visible issues': [-5, 0, 0],
        },
      },
      {
        question: 'Does the hoist operate smoothly through full travel with no unusual noise?',
        options: ['Yes — smooth and quiet', 'Intermittent hesitation', 'Unusual grinding or clicking'],
        impact: {
          'Yes — smooth and quiet': 'Mechanical components likely within spec',
          'Intermittent hesitation': 'Possible chain wear or brake drag — inspect closely',
          'Unusual grinding or clicking': 'Chain or gearbox issue — check for worn links and lubrication',
        },
        confidenceShift: {
          'Yes — smooth and quiet': [0, 0, 0],
          'Intermittent hesitation': [8, 5, 0],
          'Unusual grinding or clicking': [12, 0, 5],
        },
      },
    ],
    resolutionSteps: [
      { step: 1, text: 'LOCKOUT/TAGOUT: Lock main power in OFF position. Tag per OSHA 29 CFR 1910.147.', isLoto: true, isSafety: true },
      { step: 2, text: 'Inspect load chain full length: check for elongation, kinking, corrosion, twisted links, and damaged pockets. Use chain wear gauge — replace if elongation exceeds 3%.', isLoto: false, isSafety: false },
      { step: 3, text: 'Lubricate chain: apply chain lubricant to all links per manufacturer specification. Wipe off excess.', isLoto: false, isSafety: false },
      { step: 4, text: 'Check motor brake air gap. Measure and record. Acceptable range: 0.060"–0.180". Adjust to 0.090" if out of range.', isLoto: false, isSafety: false },
      { step: 5, text: 'Inspect hook and latch: check for deformation, throat opening, and latch spring tension. Latch must spring closed fully unassisted.', isLoto: false, isSafety: false },
      { step: 6, text: 'Remove LOTO. Cycle hoist through full travel with no load. Test upper and lower limit switches — both must stop motion reliably.', isLoto: false, isSafety: true },
      { step: 7, text: 'Complete PM inspection record: log all measurements, findings, and parts used. OSHA requires written, dated, signed report.', isLoto: false, isSafety: false },
    ],
    parts: 'Chain Lubricant — NLGI Grade 2',
    sourceRef: 'Yale Y45 Series Manual, Sections 3-1 / 4-3 / 5-2',
    faultLabel: 'Quarterly Preventive Maintenance',
    jobTime: '~45 min',
    defaultNote: 'Quarterly PM completed. Chain elongation measured at 1.9% — within spec. Applied chain lubricant. Brake air gap 0.092" — within spec. Hook and latch serviceable. All limit switches tested and functional. No deficiencies found.',
  },

  'WO-2855': {
    id: 'WO-2855',
    status: 'Scheduled',
    priority: 'Medium',
    customer: 'Valero Refinery',
    site: 'Meraux, LA',
    equipment: 'Shaw-Box Series 800 — 3-Ton Wire Rope Hoist',
    serialNumber: 'SB800-3T-7741',
    complaint: 'Annual ASME B30.16 inspection due. High-cycle application — 1,247 hours on unit since last annual. Previous annual noted wire rope at 60% estimated service life.',
    jobType: 'Annual Inspection',
    scheduledDate: 'Friday, 7:00 AM',
    lastService: '12 months ago — annual inspection',
    hoursOnUnit: 1247,
    aiReady: true,
    aiContext: '1,247 hours since last annual — exceeds 500-hour interim threshold. High-duty cycle at this site. Previous annual flagged wire rope at 60% service life. Wire rope replacement is likely this visit. Bring Part No. 800-145.',
    equipmentHistory: [
      {
        date: 'Jun 3, 2025',
        type: 'Annual Inspection',
        tech: 'M. Guidry',
        findings: 'Full ASME B30.16 annual inspection. Wire rope: no broken wires — estimated 60% service life remaining. Hook throat within spec. Brake gap 0.090". All systems functional. Passed load test.',
        partsUsed: 'None',
        hours: 598,
      },
      {
        date: 'Dec 8, 2024',
        type: 'Interim Inspection',
        tech: 'R. Fontenot',
        findings: '6-month interim inspection completed. Wire rope condition good. Brake adjusted — gap was 0.185", adjusted to 0.100". All limit switches operational.',
        partsUsed: 'None',
        hours: 311,
      },
    ],
    predictions: [
      {
        rank: 1,
        fault: 'Wire rope — inspect for broken wires, wear, and diameter reduction. Replacement likely.',
        confidence: 78,
        part: 'Wire Rope — Part No. 800-145',
        source: 'Shaw-Box 800 Series Manual, Section 4-1 (Wire Rope Inspection), p.8',
        citation: '"Replace wire rope if any of the following are found: more than 2 broken wires in any 6-rope-diameter length, kinking, bird-caging, corrosion, or reduction in diameter exceeding 1/64\" below nominal diameter."',
        severity: 'HIGH',
        safetyWarning: 'Never operate hoist with defective wire rope. Remove from service immediately if any disqualifying condition is found. Refer to ASME B30.16 Section 16-2.1.',
      },
      {
        rank: 2,
        fault: 'Drum grooves — inspect for wear and flattening at high-use positions',
        confidence: 58,
        part: null,
        source: 'Shaw-Box 800 Series Manual, Section 4-2 (Rope Drum), p.9',
        citation: '"Inspect rope drum grooves for wear or flattening. Worn grooves can damage wire rope and cause unreliable spooling under load."',
        severity: 'MEDIUM',
        safetyWarning: null,
      },
      {
        rank: 3,
        fault: 'Hook throat opening — measure and compare to ASME tolerance limit',
        confidence: 41,
        part: null,
        source: 'ASME B30.16, Section 16-1.7.2',
        citation: '"Hooks showing visible bend, twist, or throat opening exceeding 15% of original dimension shall be removed from service."',
        severity: 'LOW',
        safetyWarning: 'Any hook showing deformation or cracking must be removed from service immediately.',
      },
    ],
    adaptiveQuestions: [
      {
        question: 'When was the wire rope last replaced?',
        options: ['Within last 12 months', '1–2 years ago', 'Unknown / no record'],
        impact: {
          'Within last 12 months': 'Rope still within service life — focus on other inspection items',
          '1–2 years ago': 'Rope at end of estimated service life — replacement likely required (+15% on fault 1)',
          'Unknown / no record': 'Treat as end-of-life — thorough inspection required before any decision',
        },
        confidenceShift: {
          'Within last 12 months': [-20, 0, 0],
          '1–2 years ago': [15, 0, 0],
          'Unknown / no record': [10, 0, 0],
        },
      },
      {
        question: 'Are any broken wires visible on the rope surface?',
        options: ['Yes — broken wires visible', 'No — rope appears intact', 'Not yet inspected'],
        impact: {
          'Yes — broken wires visible': 'Wire rope must be replaced — do not operate (+20% on fault 1)',
          'No — rope appears intact': 'Proceed with full measurement — internal wear may still require replacement',
          'Not yet inspected': 'Rope inspection is first task on-site',
        },
        confidenceShift: {
          'Yes — broken wires visible': [20, 0, 0],
          'No — rope appears intact': [-5, 0, 0],
          'Not yet inspected': [0, 0, 0],
        },
      },
    ],
    resolutionSteps: [
      { step: 1, text: 'LOCKOUT/TAGOUT: Lock main power in OFF position. Tag per OSHA 29 CFR 1910.147 and ASME B30.16.', isLoto: true, isSafety: true },
      { step: 2, text: 'Inspect wire rope full length: check for broken wires, kinking, corrosion, bird-caging, and diameter reduction. Use wire rope gauge. Remove from service if any disqualifying condition found.', isLoto: false, isSafety: true },
      { step: 3, text: 'Inspect drum grooves for wear and flattening. Note condition and record.', isLoto: false, isSafety: false },
      { step: 4, text: 'Measure hook throat opening. Record dimension. Any opening exceeding 15% over nominal requires immediate hook replacement per ASME B30.16.', isLoto: false, isSafety: true },
      { step: 5, text: 'Check motor brake: measure air gap, inspect friction disc for wear. Verify brake holds rated load with no drift.', isLoto: false, isSafety: false },
      { step: 6, text: 'Test all limit switches and safety devices through full cycle of operation.', isLoto: false, isSafety: false },
      { step: 7, text: 'Remove LOTO. Perform rated load test per ASME B30.16. Hoist must hold load with no drift and stop on limit.', isLoto: false, isSafety: true },
      { step: 8, text: 'Complete ASME B30.16 annual inspection form. Written, dated, signed report is legally required. Record all measurements.', isLoto: false, isSafety: false },
    ],
    parts: 'Wire Rope — Part No. 800-145',
    sourceRef: 'Shaw-Box 800 Series Manual, Section 4-1 + ASME B30.16',
    faultLabel: 'Annual ASME B30.16 Inspection',
    jobTime: '~90 min',
    defaultNote: 'Annual ASME B30.16 inspection completed. Wire rope: 9 broken wires over 2 sections — replaced with Part No. 800-145. Hook throat within spec (measured 1.48"). Brake gap 0.095" — within spec. All limit switches functional. Rated load test passed. Inspection form completed and signed.',
  },

  'WO-2856': {
    id: 'WO-2856',
    status: 'Scheduled',
    priority: 'High',
    customer: 'BASF Chemical',
    site: 'Geismar, LA',
    equipment: 'Coffing JLM Series — 2-Ton Electric Chain Hoist',
    serialNumber: 'JLM-2T-0441',
    complaint: 'Upper limit switch fails to stop hook at top of travel. Hook bypasses upper limit — risk of two-blocking. Unit removed from service by site safety officer.',
    jobType: 'Corrective Repair',
    scheduledDate: 'Tomorrow, 2:00 PM',
    lastService: '5 months ago — routine PM',
    hoursOnUnit: 412,
    aiReady: true,
    aiContext: 'Unit pulled from service by site safety — two-blocking risk is an immediate personnel hazard. Limit switch cam adjustment is the most common cause on JLM units at this age. Inspect cam position before any disassembly.',
    equipmentHistory: [
      {
        date: 'Jan 8, 2026',
        type: 'Routine PM',
        tech: 'J. Thibodaux',
        findings: 'Full PM completed. All limit switches functional and tested. Chain elongation within spec. No deficiencies found at time of inspection.',
        partsUsed: 'Chain lubricant',
        hours: 334,
      },
      {
        date: 'Aug 15, 2025',
        type: 'Corrective Repair',
        tech: 'D. Broussard',
        findings: 'Replaced UP contactor — coil burned out. Tested all functions after repair. Limit switches normal.',
        partsUsed: 'Contactor — Part No. JLM-C12',
        hours: 218,
      },
    ],
    predictions: [
      {
        rank: 1,
        fault: 'Upper limit switch cam worn or shifted — no longer actuating switch lever at top of travel',
        confidence: 81,
        part: 'Limit Switch Cam — Part No. JLM-409',
        source: 'Coffing JLM Series Manual, Section 6-3 (Limit Switch Adjustment), p.17',
        citation: '"If the upper limit switch does not trip, inspect the cam actuator for wear or misalignment. A worn or shifted cam will not contact the switch lever at the correct point in travel."',
        severity: 'HIGH',
        safetyWarning: 'DO NOT operate hoist until upper limit switch is verified functional. Two-blocking can cause wire rope or chain failure and a dropped load. OSHA 29 CFR 1910.179 requires all limit switches to be functional before returning hoist to service.',
      },
      {
        rank: 2,
        fault: 'Limit switch contacts burned or corroded — circuit not breaking on actuation',
        confidence: 65,
        part: 'Limit Switch Assembly — Part No. JLM-410',
        source: 'Coffing JLM Series Manual, Section 6-3, p.17',
        citation: '"Inspect switch contacts for pitting or corrosion. Contaminated contacts may fail to break the circuit even when the cam actuates correctly."',
        severity: 'MEDIUM',
        safetyWarning: 'Verify switch breaks the circuit with a continuity tester before reassembly.',
      },
      {
        rank: 3,
        fault: 'Control circuit wiring fault between limit switch and contactor',
        confidence: 38,
        part: null,
        source: 'Coffing JLM Series Manual, Section 6-5 (Control Circuit), p.19',
        citation: '"Trace limit switch wiring from switch terminals to contactor. Check for chafed insulation, loose connections, or open conductors."',
        severity: 'LOW',
        safetyWarning: null,
      },
    ],
    adaptiveQuestions: [
      {
        question: 'Does the hoist stop when you manually depress the limit switch lever by hand?',
        options: ['Yes — stops immediately', 'No — no response', 'Not tested yet'],
        impact: {
          'Yes — stops immediately': 'Switch itself works — cam position or wiring is the issue (+15% on fault 1)',
          'No — no response': 'Switch contacts likely burned or circuit fault (+18% on fault 2)',
          'Not tested yet': 'Manual test should be first diagnostic step on-site',
        },
        confidenceShift: {
          'Yes — stops immediately': [15, -10, 5],
          'No — no response': [-5, 18, 12],
          'Not tested yet': [0, 0, 0],
        },
      },
      {
        question: 'Is the cam actuator visibly worn, chipped, or shifted from its mounting position?',
        options: ['Yes — visibly damaged or shifted', 'No visible damage', 'Cannot see clearly'],
        impact: {
          'Yes — visibly damaged or shifted': 'Cam replacement confirmed (+18% on fault 1)',
          'No visible damage': 'Focus on switch contacts and wiring (+10% on fault 2)',
          'Cannot see clearly': 'Full disassembly required for inspection',
        },
        confidenceShift: {
          'Yes — visibly damaged or shifted': [18, -5, 0],
          'No visible damage': [-8, 10, 5],
          'Cannot see clearly': [0, 0, 0],
        },
      },
    ],
    resolutionSteps: [
      { step: 1, text: 'LOCKOUT/TAGOUT: Lock main power in OFF position. Tag per OSHA 29 CFR 1910.147. Two-blocking hazard — keep all personnel clear of hook path during testing.', isLoto: true, isSafety: true },
      { step: 2, text: 'Open limit switch housing cover. Visually inspect cam actuator for wear, chipping, or shifted position on the shaft.', isLoto: false, isSafety: false },
      { step: 3, text: 'Manually depress limit switch lever — use continuity tester to confirm circuit breaks. If circuit does not break: replace switch assembly (Part No. JLM-410).', isLoto: false, isSafety: false },
      { step: 4, text: 'If cam is worn or shifted: replace cam (Part No. JLM-409). Align cam so lever is actuated at correct hook position — approximately 2" before upper mechanical stop.', isLoto: false, isSafety: false },
      { step: 5, text: 'Inspect all limit switch wiring from switch terminals to contactor. Check for chafed insulation, loose terminals, or open conductors.', isLoto: false, isSafety: false },
      { step: 6, text: 'Reinstall cover. Remove LOTO. Test upper limit switch through 3 complete cycles — hoist must stop reliably before reaching upper mechanical stop.', isLoto: false, isSafety: true },
      { step: 7, text: 'Document all findings, parts replaced, and test results per OSHA requirements before returning unit to service.', isLoto: false, isSafety: false },
    ],
    parts: 'Limit Switch Cam — Part No. JLM-409',
    sourceRef: 'Coffing JLM Series Manual, Section 6-3, p.17',
    faultLabel: 'Upper Limit Switch Repair',
    jobTime: '~35 min',
    defaultNote: 'Found limit switch cam worn and rotated out of position on shaft. Replaced cam (Part No. JLM-409), aligned to actuate switch lever at correct position in travel. Switch contacts clean. Tested upper limit through 3 full cycles — stops reliably before upper mechanical stop. Unit returned to service.',
  },
}

export const TECHNICIAN_HISTORY = [
  {
    id: 'WO-2831',
    customer: 'Dow Chemical',
    site: 'Freeport, TX',
    equipment: 'Yale Y80 Series — 3-Ton Wire Rope Hoist',
    jobType: 'Corrective Repair',
    date: 'Mar 3, 2025',
    outcome: 'Load brake friction washers replaced due to glazing. No drift on test run.',
    partsUsed: 'Friction Washer (x2) — Part No. 800-235',
    status: 'Completed',
  },
  {
    id: 'WO-2819',
    customer: 'Westlake Chemical',
    site: 'Sulphur, LA',
    equipment: 'Shaw-Box Series 800 — 2-Ton Wire Rope Hoist',
    jobType: 'Routine PM',
    date: 'Feb 14, 2025',
    outcome: 'Quarterly PM completed. Chain elongation within spec. Brake air gap 0.092". No deficiencies.',
    partsUsed: 'Chain lubricant',
    status: 'Completed',
  },
  {
    id: 'WO-2804',
    customer: 'ExxonMobil',
    site: 'Baton Rouge, LA',
    equipment: 'World Series Double Girder Crane — 10-Ton',
    jobType: 'Annual Inspection',
    date: 'Jan 22, 2025',
    outcome: 'ASME B30.2 annual inspection. Wire rope replaced — exceeded service life. Load test passed.',
    partsUsed: 'Wire Rope — Part No. 800-145',
    status: 'Completed',
  },
  {
    id: 'WO-2791',
    customer: 'LyondellBasell',
    site: 'Houston, TX',
    equipment: 'Coffing JLM Series — 2-Ton Chain Hoist',
    jobType: 'Corrective Repair',
    date: 'Jan 8, 2025',
    outcome: 'UP contactor coil burned out. Replaced contactor assembly. All functions tested normal.',
    partsUsed: 'Contactor — Part No. JLM-C12',
    status: 'Completed',
  },
]

export const KNOWLEDGE_BASE = {
  totalDocuments: 4,
  totalPages: 180,
  lastUpdated: 'May 14, 2026',
  documents: [
    { name: 'Shaw-Box Series 800 Wire Rope Hoist Manual', type: 'Manual', equipment: 'Wire Rope Hoist', pages: 44, status: 'Indexed', uploaded: 'May 14, 2026', source: 'SharePoint' },
    { name: 'Yale Y80 Series Wire Rope Hoist Manual',     type: 'Manual', equipment: 'Wire Rope Hoist', pages: 38, status: 'Indexed', uploaded: 'May 14, 2026', source: 'SharePoint' },
    { name: 'Yale Global King Hoist Manual',              type: 'Manual', equipment: 'Heavy Duty Hoist', pages: 52, status: 'Indexed', uploaded: 'May 14, 2026', source: 'Corporate Drive' },
    { name: 'World Series 3D Double Girder Trolley Manual', type: 'Manual', equipment: 'Bridge Crane',  pages: 46, status: 'Indexed', uploaded: 'May 14, 2026', source: 'Corporate Drive' },
  ],
  coverageGaps: [
    { equipment: 'Industrial Elevators',      status: 'No documents indexed',                   priority: 'High',   count: 0 },
    { equipment: 'Dock & Door Systems',        status: 'No documents indexed',                   priority: 'Medium', count: 0 },
    { equipment: 'Yale Global King (500T+)',   status: '1 document — service bulletins missing', priority: 'Medium', count: 1 },
  ],
}

export const ANALYTICS = {
  totalQueries: 847,
  avgResponseTime: '3.2s',
  firstVisitResolutionRate: '73%',
  callbackReduction: '31%',
  estimatedAnnualSavings: '$412,000',
  topQuestions: [
    { label: 'Motor brake adjustment procedure', count: 142 },
    { label: 'Wire rope inspection criteria',    count: 98  },
    { label: 'Overload clutch slipping',         count: 76  },
    { label: 'Load drift troubleshooting',       count: 61  },
    { label: 'Contactor replacement',            count: 54  },
  ],
  mostAccessedManual: 'Shaw-Box Series 800',
  mostAccessedCount: 142,
  queriesByMonth: [38, 52, 71, 89, 103, 124, 142, 119, 109],
}
